# Generated by Django 5.1.5 on 2025-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_todo_completed_image_todo_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="completed_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="todo/completed_images",
                verbose_name="완료_이미지",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="todo/no_image/NO-IMAGE.gif",
                null=True,
                upload_to="todo/thumbnails",
                verbose_name="썸네일_이미지",
            ),
        ),
    ]
